# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"  # Title of the link.
  url = "#about"  # Widget Page folder name.
  weight = 56  # Position of the link in the navigation bar.
  identifier = "about"

[[main]]
  name = "Blog"
  url = "post/"
  weight = 62

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 60
  parent = "about"

[[main]]
  name = "Writing"  # Title of the link.
  url = "writing/"  # Widget Page folder name.
  weight = 70  # Position of the link in the navigation bar.
  identifier = "written content"

[[main]]
  name = "Data"  # Title of the link.
  url = "data/"  # Widget Page folder name.
  weight = 2  # Position of the link in the navigation bar.
  parent = "written content"

[[main]]
  name = "Projects"  # Title of the link.
  url = "projects/"  # Widget Page folder name.
  weight = 69  # Position of the link in the navigation bar.
  parent = "written content"

[[main]]
  name = "Science"  # Title of the link.
  url = "science/"  # Widget Page folder name.
  weight = 7  # Position of the link in the navigation bar.
  parent = "written content"

[[main]]
  name = "Class"  # Title of the link.
  url = "class/"  # Widget Page folder name.
  weight = 12  # Position of the link in the navigation bar.
  parent = "written content"

[[main]]
  name = "Services"  # Title of the link.
  url = "services/"  # Widget Page folder name.
  weight = 72  # Position of the link in the navigation bar.

[[main]]
  name = "CV"  # Title of the link.
  url = "cv/"  # Widget Page folder name.
  weight = 71  # Position of the link in the navigation bar.
  parent = "about"

[[main]]
  name = "Current Reading List"  # Title of the link.
  url = "readinglist/"  # Widget Page folder name.
  weight = 73  # Position of the link in the navigation bar.
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
