# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 60

[[main]]
  name = "Writing"  # Title of the link.
  url = "writing/"  # Widget Page folder name.
  weight = 98  # Position of the link in the navigation bar.
  identifier = "data"
  identifier = "science"

[[main]]
  name = "Data"  # Title of the link.
  url = "data/"  # Widget Page folder name.
  weight = 2  # Position of the link in the navigation bar.
  parent = "Writing"

[[main]]
  name = "Projects"  # Title of the link.
  url = "projects/"  # Widget Page folder name.
  weight = 69  # Position of the link in the navigation bar.

[[main]]
  name = "Science"  # Title of the link.
  url = "science/"  # Widget Page folder name.
  weight = 7  # Position of the link in the navigation bar.
  parent = "writing"

[[main]]
  name = "About"  # Title of the link.
  url = "about/"  # Widget Page folder name.
  weight = 56  # Position of the link in the navigation bar.
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
